services:
  mysql:
    image: mysql:8.3.0
    container_name: resume_analyzer_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: resume_analysis
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: